#
# Linux System Manager Configuration File
#

# Log level settings (0: INFO, 1: WARNING, 2: ERROR)
LOG_LEVEL=0

# Default ports for socket chat server
DEFAULT_PORT=9099

# Backup destination path
BACKUP_PATH=./backups
